### ISSUE TITLE
Cannot access Kinesis. Status Code: 400; Error Code: UnrecognizedClientException

### ISSUE THREAD

**Issue by Igorock** [qubole/kinesis-sql#12]
We configured IAM role with full access to Kinesis and assigned it to our ec2-user. But when it wants to connect to kinesis with you library we get an error:
` WARN KinesisReader: Error while Describe stream The security token included in the request is invalid. (Service: AmazonKinesis; Status Code: 400; Error Code: UnrecognizedClientException`
We don't set any keys.
Please help

**Comment by itsvikramagr** [comment]
@Igorock - Current Implementation still does not support IAM role. #4 is raised for the same. I am planning to raise a PR for #4 by end of this week.

**Comment by itsvikramagr** [comment]
Committed the change in master

**Comment by Igorock** [comment]
still have the same error after updating master branch
