### ISSUE TITLE
Support for Continuous Streaming

### ISSUE THREAD

**Issue by itsvikramagr** [qubole/kinesis-sql#14]
Spark 2.3.x supports continuous streaming (https://spark.apache.org/releases/spark-release-2-3-0.html#structured-streaming)

We need to add Support of Continous Steaming when Source is Kinesis.

**Comment by ggeorgiadis** [comment]
This is a nice feature. Maybe we can do it in conjunction with support for fan-out which was released today [release article](https://aws.amazon.com/about-aws/whats-new/2018/08/stream_data_65_faster_with_5x_higher_fan_out_using_new_kinesis_data_streams_features/). Shall we make a new ticket for this?

**Comment by itsvikramagr** [comment]
Let's have a new ticket for "support for fan-out"  as it can be used for both micro batch and continuous streaming. 

I have already done some work for continuous streaming. Planning to raise a PR for the same by EOD today.

**Comment by Gauravshah** [comment]
added support in https://github.com/qubole/kinesis-sql/pull/15
