### ISSUE TITLE
Certificate Verify Failed

### ISSUE THREAD

**Issue by ggeorgiadis** [qubole/kinesis-sql#17]
It seems that an aws deprecation is causing failures while using the sink! You can see the following errors by the KPL:
`[2018-08-16 12:21:06.864637] [0x0000700009927000] [error] [http_client.cc:148] Failed to open connection to kinesis.eu-west-1.amazonaws.com:443 : certificate verify failed
[2018-08-16 12:21:06.964754] [0x0000700009927000] [error] [http_client.cc:148] Failed to open connection to kinesis.eu-west-1.amazonaws.com:443 : certificate verify failed`

As far as I can see the versions have been updated in the master branch of Spark [4d8ae0d1c846560e1cac3480d73f8439968430a6](https://github.com/apache/spark/commit/4d8ae0d1c846560e1cac3480d73f8439968430a6) but they are not pulled in this library's pom therefore causing the errors.

I fixed it by hardcoding the latest kpl and aws sdk versions in branch 2.2.1 which fixed the issue.

Shall I make a PR for this?

**Comment by itsvikramagr** [comment]
Thanks for this. Yeah please start a PR.
