### ISSUE TITLE
Protobuf version conflict for deaggregation of Kinesis records 

### ISSUE THREAD

**Issue by peay** [qubole/kinesis-sql#23]
Hello,

Great library! I am trying to use it with aggregated Kinesis records, and I am running into some kind of conflict, compiling for Spark 2.3.1. When the aggregated record is read:

```
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/ProtocolStringList
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.clientlibrary.types.UserRecord.deaggregate(UserRecord.java:235)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.clientlibrary.types.UserRecord.deaggregate(UserRecord.java:176)
	at org.apache.spark.sql.kinesis.KinesisReader.deaggregateRecords(KinesisReader.scala:151)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:147)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:119)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
...
```

I see that `spark-parent:2.3.0`has `<protobuf.version>2.5.0</protobuf.version>` (which doesn't have `ProtocolStringList` as far as I understand), while the amazon kinesis client library has `2.6.1`.

Any suggestion on how to best fix this? Using the JAR for 2.6.1 directly in `$SPARK_HOME/jars/` seems to work but I am a bit worried about unexpected consequences of using a newer version overall.

**Comment by itsvikramagr** [comment]
One way is that we can include protobuf in this library and shade it. We can make the following changes. Can you please try it and let me know if this works for you. cc @peay 

`diff --git a/pom.xml b/pom.xml
index e396606..80e173c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -148,6 +148,7 @@
                   <include>com.amazonaws:aws-java-sdk-core:*</include>
                   <include>com.amazonaws:aws-java-sdk-sts:*</include>
                   <include>com.fasterxml.jackson.dataformat:*:*</include>
+                  <include>com.google.protobuf:*:*</include>
                 </includes>
                 </artifactSet>
                 <relocations>
@@ -165,6 +166,10 @@
                         <include>com.amazonaws.**</include>
                       </includes>
                     </relocation>
+                    <relocation>
+                      <pattern>com.google.protobuf</pattern>
+                      <shadedPattern>org.apache.spark.sql.kinesis.shaded.google.protobuf</shadedPattern>
+                    </relocation>
                 </relocations>
                 <filters>
                   <filter>`

**Comment by peay** [comment]
I gave it a try, but that doesn't seem to work. The protobuf lib is getting shaded and included in the JAR at the relocated location, but it is not being used by the Kinesis client library. My (possibly inaccurate) understanding is that relocations using the shade plugin are only applied to code that is being compiled as part of the current project - here, the dependency to protobuf is in the already compiled JAR for the Kinesis client library I think?

**Comment by itsvikramagr** [comment]
I was hoping that it might work. But what you have interpreted makes sense. 

I guess then one of the options is to include the latest version in the classpath. Maybe you can check the difference between two protobuf version to figure out possible conflicts.

else you might need to create your shaded kinesis client library and include that in your classpath.
