### ISSUE TITLE
It takes a very long time before consumption from the stream starts

### ISSUE THREAD

**Issue by ealtamir** [qubole/kinesis-sql#24]
Although there are elements in the stream, I keep receiving empty batches for an unspecified amount of time (many minutes) and then suddenly it starts working. After that, it works as expected, the app starts consuming events from the stream immediately, if I send new events after the stream has been emptied, it takes only a few seconds to start processing them once they reach the stream. 

Could this be a problem with the library, kinesis itself or normal behavior I'm unaware of?

**Comment by itsvikramagr** [comment]
@ealtamir - have you used `TRIM_HORIZON` as startingPosition? Also what is the config used for 
`kinesis.executor.maxFetchRecordsPerShard` and `kinesis.executor.maxRecordPerRead`?

As per the doc - https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html

```The shard iterator specifies the position in the shard from which you want to start reading data records sequentially. If there are no records available in the portion of the shard that the iterator points to, GetRecords returns an empty list. It might take multiple calls to get to a portion of the shard that contains records.```

--



--



--

**Comment by itsvikramagr** [comment]
you may want to check with AWS support to see if we have any other workaround. 

For now, you may want to increase this `kinesis.executor.maxFetchTimeInMs` to say higher value depending upon your SLA. It will ensure that we make sufficient GetRecords call to get to the portion of the shard that contains records. 

If you know the velocity at which records are added in Kinesis is not high, you can reduce the time spent in each micro batch by keeping a lower value of `kinesis.executor.maxFetchRecordsPerShard`
