### ISSUE TITLE
How to increase records read per second?

### ISSUE THREAD

**Issue by HydroMeter12** [qubole/kinesis-sql#25]
Thanks for the great library. My current stream consists 50 shards, processing around 500k+ records per minute. I've setup this library in a Spark job, but it's only reading ~ 150k records per minute, how can I increase this number? Already changed all the `kinesis.executor` settings, but this didn't had any effect.

**Comment by itsvikramagr** [comment]
@HydroMeter12 - can you provide more details

- how many executors container are running. Each shard creates a task. so for maximum parallelism, you might need to run at least 50 containers.
- How much time is spent on other operations than reading from Kinesis - addBatch, getBatch,  getOffset, queryPlanning, triggerExecution, walCommit. You can look into Progress reporter for this
- Is there any AWS rate limit or errors?

**Comment by HydroMeter12** [comment]
@itsvikramagr - Thanks for the quick reply, please see more details below.

I've moved this application to a test environment with 20 shards, I see 21 tasks are generated for each job. These tasks are executed by between one and six executors, the full job is completed in ~ 15 seconds. 

`kinesis.executor.maxFetchRecordsPerShard` = 1000000000
`kinesis.executor.maxRecordPerRead` = 1000000000
`kinesis.executor.maxFetchTimeInMs` = 1000000000
`startingPosition` = TRIM_HORIZON (tried both)

Jobs are triggered by `Trigger.ProcessingTime("2 minutes")`, only the first two jobs are actually fetching data from Kinesis. I don't see any `GetRecords` calls in Kinesis after those two. The stream receives ~ 50k unique records per minute, there are also a lot of 'unprocessed" records, which I expect to be fetched by this job when using the TRIM_HORIZON setting.

I don't see any AWS rate limits or errors. Also checked the log files of the job and tasks, the only interesting messages I could found are below.

```2018-10-02T09:00:10.002+0000: [GC (Allocation Failure) 2018-10-02T09:00:10.002+0000: [ParNew: 135381K->10370K(154880K), 0.0536550 secs] 171137K->62510K(498944K), 0.0537487 secs] [Times: user=0.17 sys=0.00, real=0.06 secs]```

```18/10/02 09:00:10 WARN KinesisSourceRDD: Neither LastSequenceNumber nor LastTimeStamp was recorded.```

The main flow I want to achieve is fetching all (limited by kinesis.executor setting) of unprocessed data every 2 minutes, process the data and write it to S3. Later on I want to increase the job trigger to 15 minutes, so I only get four files generated each hour.

**Comment by itsvikramagr** [comment]
You executor's configuration does not seem to be correct as per your requirement. Based on your incoming data velocity, I think you can try following configs

kinesis.executor.maxFetchRecordsPerShard = 80k (basically you may want to try a number between 50k to 100k)
kinesis.executor.maxRecordPerRead = 10k (this configuration is per AWS API. you can't have more than 10k records per API call)
kinesis.executor.maxFetchTimeInMs = 90000 (basically you may want to try a number between 1 min to 2 min)

Also you may want to check how many tasks are running in parallel (for better SLAs, you would like to run 20 tasks in parallel)

**Comment by itsvikramagr** [comment]
@HydroMeter12 - were you able to tune your streaming job? Closing this ticket for now. you can email me any further queries  (vagrawal at qubole.com)
