### ISSUE TITLE
Mistake in example with buggy writeStream

### ISSUE THREAD

**Issue by edmondja** [qubole/kinesis-sql#26]
"kinesis
    .selectExpr("CAST(rand() AS STRING) as partitionKey","CAST(data AS STRING)").as[(String,String)]
    .groupBy("data").count()
    .writeStream
    .format("kinesis")
    .outputMode("update") 
    .option("streamName", "spark-sink-example")
    .option("endpointUrl", "https://kinesis.us-east-1.amazonaws.com")
    .option("awsAccessKeyId", [ACCESS_KEY])
    .option("awsSecretKey", [SECRET_KEY])
    .start()
    .awaitTermination()"

cannot work coz you have to get rid of the groupBy : 
"java.lang.IllegalStateException: Required attribute 'partitionKey' not found"

I would add that readStream works but writeStream do not work at all, even with simple data doing :  "streamingDdf.selectExpr("CAST(rand() AS STRING) as partitionKey","CAST(rand() AS STRING) as data")"

**Comment by itsvikramagr** [comment]
@ggeorgiadis  - do you want to take this?

**Comment by edmondja** [comment]
Writestream works but just do not complain enough. I used it on sagemaker and didnt write nothing without printing any error. Locally it works fine.

And yes I still think the groupby("data") changes the schema of the streaming dataframe..
