### ISSUE TITLE
Spark 2.4 support

### ISSUE THREAD

**Issue by adrianN** [qubole/kinesis-sql#42]
Is support for Spark 2.4 planned? Already being worked on? Do you already have an overview of what would need to be done to run with Spark 2.4?

**Comment by itsvikramagr** [comment]
2.4 is already supported. You can check out [2.4.0 branch ](https://github.com/qubole/kinesis-sql/tree/2.4.0) or [master branch ] (https://github.com/qubole/kinesis-sql/tree/master)
