### ISSUE TITLE
sink low write throughput 

### ISSUE THREAD

**Issue by levontr** [qubole/kinesis-sql#47]
I have a spark job which is reading from kinesis input  stream and simply writing it to kinesis output stream. 
The write speed to input stream is >800rec/sec. The problem is that when I am consuming from final output stream the speed is just about ~20rec/sec.
When I change kinesis sink to s3 or console, I can see very high throughput.
Here is my code:

`val kinesisDF = spark
      .readStream
      .format("kinesis")
      .option("streamName", "input_stream")
      .option("startingposition", "trim_horizon")
      .option("endpointUrl", "https://kinesis.eu-central-1.amazonaws.com")
      .option("region", "eu-central-1")
      .load()

    val kinesis2 = kinesisDF
      .selectExpr("cast (data as STRING) jsonData")
      .withColumn("data", functions.from_json(functions.col("jsonData"), dataSchema))
      .select("data.*")

    val kinesis_result = kinesis2
      .withColumn("data", functions.to_json(functions.struct("ts", "unit_name", "name", "val")))
      .withColumn("partitionKey", kinesis2 ("unit_name"))
      .selectExpr("cast (data as BINARY)", "partitionKey")
      .repartition(10)

    kinesis_result
      .select("data", "partitionKey")
      .writeStream
      .partitionBy("partitionKey")
      .option("kinesis.executor.maxConnections", "20")
      .format("kinesis")
      .option("endpointUrl", "https://kinesis.eu-central-1.amazonaws.com")
      .outputMode("append")
      .option("checkpointLocation", "s3_path")
      .option("streamName", "output_stream")
      .start()
      .awaitTermination()
`

from the spark UI i can see the following:

![kinesis](https://user-images.githubusercontent.com/11329432/56734635-b190f080-6763-11e9-9c68-af0d3c7aee10.PNG)

Another thing is that, when I run 
`aws kinesis get-records --shard-iterator "?????"`
for the output stream, I can see that records are coming sequentially and not in batch (approximate arrival times is different)

I want to understand if there are any limitations in kinesis sink part, that causes low throughput?

**Comment by itsvikramagr** [comment]
@ggeorgiadis - Can you take this one? 

@ltbus - I have not tested the sink part at scale. Have you tried increasing the value of `kinesis.executor.recordMaxBufferedTime`? Let me also try this at my end and get back with possible solutions.

**Comment by ggeorgiadis** [comment]
@ltbus Try increasing the `kinesis.executor.recordmaxbufferedtime` to a higher number. The default is 1000 ms. We might need to increase the default configuration to a higher number.

**Comment by ltbus** [comment]
@ggeorgiadis I already tried options like `.option("kinesis.executor.recordMaxBufferedTime","10000")` and `.option("kinesis.executor.maxFetchTimeInMs", "3000")`
but the result is the same

**Comment by ltbus** [comment]
As a side note, when I am implementing kinesis sink using `ForeachWriter` i can achieve much better performance

**Comment by itsvikramagr** [comment]
@levontr - do you want to contribute the new implementation to this repo? We can have a flag/option using which the user can pick the implementation for his application.

**Comment by ronyx18** [comment]
It is writing very slow for me as well. I ran 2 programs parallely , both reading from same kafka topic and one of them writing to s3 and the other to kinesis. Kinesis one is very slow i.e. 1/20th of the speed of the other one.
I have tried all the available configurations : kinesis.executor.maxConnections , kinesis.executor.recordMaxBufferedTime . But still the same.
Can anyone provide me the foreachWriter sample code to write to Kinesis for spark 2.2, please?

**Comment by abhishekd0907** [comment]
@levontr @ronyx18 

I've raised PR for this issue. #81
