### ISSUE TITLE
source startingposition doesn't work for LATEST

### ISSUE THREAD

**Issue by levontr** [qubole/kinesis-sql#48]
When I try to read stream from latest point with `.option("startingposition", "LATEST")` , it doesn't read from latest point but from some other point, seems from some checkpoint.
I reset the application name or `.option("checkpointLocation", "hdfs_path")`, but it doesn't help, consumption  does not start from the latest point in stream.

In contrast, when I put "TRIM_HORIZON", I can observe records from the beginning of stream.

Here is my source code

` val kinesisDF = spark
      .readStream
      .format("kinesis")
      .option("streamName", "input_stream")
      .option("startingposition", "LATEST")
      .option("region", "eu-central-1")
      .load()`

How can I force to read from latest point?

**Comment by levontr** [comment]
Any thoughts ?

**Comment by itsvikramagr** [comment]
@levontr - I would need more details.  How have you inferred that it's not starting from latest point? What exactly is your expectations?

Also, can you share the shard offsets of initial batches.

**Comment by itsvikramagr** [comment]
As a side note, I intend to start a PR on #3 soon which might help to resolve any discrepancy.

**Comment by levontr** [comment]
@itsvikramagr 

I have kinesis input stream where I push the time series records. When I consume the stream I can see almost no latency between records timestamp and current system timestamp. When I restart the job, I expect to observe records with timestamp close enough to current system timestamp, but i see records from a few hours back. So for sure not the latest records pushed to input stream.

Based on the code in `KinesisSourceProvider.scala` i can see that in case of `.option("startingposition", "LATEST")` it picks the current timestamp as starting position. Which field it is in kinesis stream? `"approximateArrivalTimestamp"` or different ?

**Comment by itsvikramagr** [comment]
Do you change the checkpoint location when you restart the job,?  Structured streaming job with same checkpoint location will restart from last processed record in the previous run and not from latest...
If you have to always restart from Latest, you have to change the checkpoint location every-time you restart (or delete the previous folder).

AFAIK, it should be approximateArrivalTimestamp which is the server side timestamp. We can check the amazon kinesis docs again to verify it

**Comment by levontr** [comment]
I change every time checkpoint location. But this  checkpoint location option is for writing the stream right? not to have duplicate writes. But in the first place I have a problem of duplicate reads, i tried to set this option also while reading but nothing changes.

**Comment by levontr** [comment]
In the documentation it doesn't clearly say what timestamp it is, but i guess it is approximateArrivalTimestamp

**Comment by levontr** [comment]
even if there was a checkpoint issue, when i stop and start the job immediately, the checkpoint should have been very close to no and no way back a few hours.

**Comment by levontr** [comment]
apparently the checkpoint wasn't getting updated to the new one and always was reading from the old one. So I deleted all of them restarted and seems now is working. I will close the issue and reopen in case it's reproducible again.
Thanks for your support
