### ISSUE TITLE
Kinesis sink bug: child process has been shutdown (including fix)

### ISSUE THREAD

**Issue by jamescauwelier** [qubole/kinesis-sql#52]
There is a [merged PR](https://github.com/qubole/kinesis-sql/pull/5), that after merging received some more commits fixing a bug.

The bug, as described in the PR, manifests itself like so:

```
The child process has been shutdown and can no longer accept messages.
```

As the PR mentions, the fix should be implemented, but does still need to be merged into the code.

**Comment by itsvikramagr** [comment]
@jamescauwelier - which commit(fix) are you talking about? Can you start a PR with the fix so that I can merge it now?

**Comment by itsvikramagr** [comment]
Closing this issue since there is no update on the issue. Please open a new issue if you are still facing the same problem.

**Comment by jamescauwelier** [comment]
Instead of closing issues, you should maybe stabilize your software.  The possible fix is already mentioned.

**Comment by itsvikramagr** [comment]
@jamescauwelier - I would appreciate it if you can elaborate on the issue in detail. If there is already a fix available can you provide the link or else can you start afresh PR? This connector is open-sourced for everyone to use. It would help if you can contribute if you have identified the problem and you know about the fix.

**Comment by jamescauwelier** [comment]
Reread the first message.  That has all the information you need.  I am not going to contribute as I have switched to kafka for my personal projects.  If I hadn't, I'd probably start from scratch on a new DynamoDB connector as a serious overhaul and rethinking of this project is needed imho.
