### ISSUE TITLE
Kinesis Consumer lag behavior in multiple regions

### ISSUE THREAD

**Issue by spjegan** [qubole/kinesis-sql#54]
Hi, 
We have a stream in 5 regions and the application (deployed in one region) reads from these 5 regions and does a union on the streams and then performs the operations.

What we see from time to time is that the application lags in some regions. It is not necessarily a region with high workload. We use the metric "iteratorAgeMilliSeconds" to find the lag. And as you can see from the attached image, the job is able to catchup to the current traffic, and then immediately falls behind. This lag at times is multiple hours. This abrupt increase and decrease within few seconds is surprising. I am trying to understand why it behaves like this and how we can keep the lag under a minute.

Below are the 3 configurations we use. We have already tried tweaking these params.

```
          maxRecordsPerRead = "9000"
          maxRecordsReadPerShard = "100000"
          maxFetchTimeInMs = "20000"
```
Please let me know if you need any additional parameters.

<img width="390" alt="kinesis" src="https://user-images.githubusercontent.com/1721264/64876394-e06d0d80-d603-11e9-82ec-8dc250783e52.png">

**Comment by itsvikramagr** [comment]
@spjegan - Thanks for reporting it. 

1. What is the spark version?
2. Have you tried pulling the latest code for kinesis-sql and running the job? There were few fixes made in the past few months which I think might solve your issue.

Will need for some more data-points if you see the same issue even with the latest kinesis-sql.

**Comment by spjegan** [comment]
Thanks @itsvikramagr 
1. We use Spark 2.4.0.
2. Not yet. Will try pulling the latest code and test. Will update here on the progress.

**Comment by spjegan** [comment]
@itsvikramagr We have just deployed the latest code in our environment. Usually we see this behavior after the application has been running for a week or so. So we will monitor this for at least a week and then update here.

Thanks.

**Comment by itsvikramagr** [comment]
@spjegan 

Also, can you increase the maxRecordsReadPerShard = "100000" to some larger value? say 1,000,000 and keep `maxRecordsPerRead` as `10000` (10k is maximum records per read API call allowed by AWS).

**Comment by itsvikramagr** [comment]
Also, make sure that you are using the correct config names or else the library will take the default value which might not be optimal for your use-case.

kinesis.executor.maxFetchTimeInMs 
kinesis.executor.maxFetchRecordsPerShard 
kinesis.executor.maxRecordPerRead

**Comment by spjegan** [comment]
@itsvikramagr We still see the same behavior with the latest version of the library (2.4.0 branch). Have attached the screenshot of IteratorAgeMS below.

Thank you so much for the suggestions. The config names are correct. The ones I have pasted above is the application config. These are correctly set when the streams are created.

We will try changing `maxRecordsReadPerShard` to 1,000,000 and see the behavior. But this has a risk of hitting `ProvisionedThroughputExceeded` exceptions as it is possible that the library makes more than 5 calls/second, especially because `GetRecords` response time is mostly under 100 ms.

I guess changing `maxRecordsPerRead` to 10,000 also may cause `ProvisionedThroughputExceeded` exceptions too often as there is a limit of 10 MB per GetRecords call.

Will try the `maxRecordsReadPerShard` suggestion and get back here. Would really appreciate your help on any other suggestions too. Please let me know if you need any other details.

![Kinesis](https://user-images.githubusercontent.com/1721264/65899765-462df900-e369-11e9-8f0a-149da8c884d9.png)

**Comment by itsvikramagr** [comment]
on `maxRecordsPerRead`, yeah you can fix a value depending upon the expected maximum size of your record. 10K per read is the maximum that you can set. You can reduce it such that the total size of the response is less than 10 MB.

`maxRecordsReadPerShard` - What is your ingestion rate, we need to make sure spark is able to process at a rate more than the ingestion rate. maxRecordsReadPerShard is one the knob to increase the processing. We have backoff if we hit ProvisionedThroughputExceeded exception. 
 maxRecordsReadPerShard = 100k seems to be less for your use-case. We should consider increasing it.

**Comment by spjegan** [comment]
Hi @itsvikramagr 
Our ingestion rate in the most busy region is only around 100K records per second. But this is over the entire Stream (across all shards) in the region. But will definitely try increasing `maxRecordsReadPerShard` as you have suggested.

Thanks,
Jegan

**Comment by spjegan** [comment]
Hi @itsvikramagr 
Unfortunately setting `maxRecordsReadPerShard` to 1M did not help. I still see huge lags in the Consumer side. The application runs fine for some time(sometimes days together) and then slowly the lag accumulates and then it becomes unmanageable.

Do you have any other recommendations or suggestions? Please let me know if you need any other information or metric from my side.

**Note:**  I do not see any latency issues from `getRecords`.

Thanks,
Jegan

**Comment by itsvikramagr** [comment]
@spjegan - I would need into logs and other metrics to understand it better. Let me ping you directly on your email-id (the one mentioned here https://github.com/spjegan) and ask you for more info.

**Comment by spjegan** [comment]
@itsvikramagr Sure. Lets talk about this over email.
