### ISSUE TITLE
reprocessing of already processed records after scaling the shards.

### ISSUE THREAD

**Issue by PranshuAdhikari** [qubole/kinesis-sql#60]
We are currently working on a streaming job that reads data from the Kinesis stream using the connector library of version 2.4.0. We have observed that the records which were already processed within the previous batches are processed again whenever the shards are scaled up or down. This happens irrespective of the offset check-pointing. Whenever new shards are created, the records of the closed/parent shards are read again using the start position as TRIM_HORIZON.

**Comment by itsvikramagr** [comment]
Thanks @PranshuAdhikari for reporting the issue. #63 fixes the issue.
