### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by israel** [qubole/kinesis-sql#64]
Hi,

It seems that only the pom files are published to maven central thus --packages option with spark-submit is not working.

Thanks,

Israel

**Comment by itsvikramagr** [comment]
Yeah, I also noticed it a couple of days back. I will be fixing it this week.

**Comment by israel** [comment]
Thanks

**Comment by safaktrgt** [comment]
Any progress on this issue ?
(or am i asking too early? -- if that's the case i'm sorry -- )

**Comment by itsvikramagr** [comment]
I have published the jars now. (https://search.maven.org/artifact/com.qubole.spark/spark-sql-kinesis_2.11) Should be synced to mvnrepository soon

**Comment by israel** [comment]
thx
