### ISSUE TITLE
passing aws_iam_role instead of awsSecretKey/awsAccessKeyId

### ISSUE THREAD

**Issue by cezgit** [qubole/kinesis-sql#69]
Not in the docs so I'm asking here... could we use an option with aws_iam_role instead of the aws credentials? As in:
```
val kinesisDF = spark.readStream
    .format("kinesis")
    .option("streamName",streamName)
    .option("initialPosition",initialPosition)
    .option("region", regionName)
    .option("aws_iam_role", roleArn)
    .load()
```
There's another similar issue that's been asked before but was closed without providing a solution.

Thanks.

**Comment by itsvikramagr** [comment]
@cezgit - you can use `awsstsrolearn` & `awsstssessionname` to specify IAM role ARN and Session name. In case you dont specify anything - IAM role, or IAM keys, the module will try to get instance credentials. 

We need to put it in the doc.

https://github.com/qubole/kinesis-sql/blob/master/src/main/scala/org/apache/spark/sql/kinesis/KinesisSourceProvider.scala#L102
