### ISSUE TITLE
Add project to maven repository

### ISSUE THREAD

**Issue by ggeorgiadis** [qubole/kinesis-sql#7]
It would be nice to submit the project to the maven repository to make it easier to include it in existing projects without having use the --jars flag.

**Comment by nedkoh** [comment]
Completely agree. If this is to be a formal library with continuous release process it needs to be added to CI and included in a repository

**Comment by itsvikramagr** [comment]
Sure. Let me prioritise this ask.

**Comment by pbrose** [comment]
+1 any update?

**Comment by itsvikramagr** [comment]
I have started to make changes to fix it. It will be done in the next 4-5 days.
