### ISSUE TITLE
Not supporting sessionToken/securityToken?

### ISSUE THREAD

**Issue by guoming-xu** [qubole/kinesis-sql#70]
I'm experimenting this locally where only session based token is available. The credential details are stored in the credential file with a profile name. I don't see a way to authenticate this way?

**Comment by itsvikramagr** [comment]
@guoming-xu - I would encourage you to start a PR for the same. Please let me know if you need any help in getting started.

**Comment by itsvikramagr** [comment]
resolved via #72
