### ISSUE TITLE
Support scala 2.12?

### ISSUE THREAD

**Issue by arnehuang** [qubole/kinesis-sql#80]
Any thoughts on building with scala 2.12 since 2.11 is deprecated in spark now

**Comment by itsvikramagr** [comment]
@arnehuang 

Are you looking for scala 2.12 for spark 3? or do you want to build older spark versions with scala 2.12 as well?

I will soon start a PR for spark 3 and publish the maven artifact.

**Comment by arnehuang** [comment]
For me personally I was looking for a spark 2.4 build with scala 2.12. Also I'm very new so I don't really know if this is something I can do easily myself?

More broadly, I'm not sure what the adoption rate for scala 2.12 builds is, however I see big providers like amazon EMR building spark with scala 2.12 now (e.g. [here](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-6x.html)) with spark 2.4.4, so I was wondering ii you plan to build older spark versions with scala 2.12

**Comment by chadlagore** [comment]
We also tend to compile this JAR for Spark 2.4/Scala 2.12 and publish it to our internal artifactory for use on EMR.

**Comment by itsvikramagr** [comment]
You can use scala 2.12 with Spark 3 branch/jar #92
