### ISSUE TITLE
Spark Streaming doesn't receive messages

### ISSUE THREAD

**Issue by Igorock** [qubole/kinesis-sql#9]
I followed your tutorial but my Spark application doesn't consume messages from Kinesis, however another Java application works fine. I even able to view stream schema with printSchema method:

root
 |-- data: binary (nullable = true)
 |-- streamName: string (nullable = true)
 |-- partitionKey: string (nullable = true)
 |-- sequenceNumber: string (nullable = true)
 |-- approximateArrivalTimestamp: timestamp (nullable = true)

But that's it, and no errors.  Please help

**Comment by itsvikramagr** [comment]
Do you have any stack trace?

**Comment by Igorock** [comment]
No errors, no warnings

**Comment by Igorock** [comment]
Sorry, after enabling appropriate logging level I got:
`WARN  KinesisReader:66 - Error while Describe stream The security token included in the request is invalid. (Service: AmazonKinesis; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 0310e112-b788-4214-8ca5-31001626179f)`

It works if set keys explicitly in the code but it ignores keys in environment variables. Is it possible to use keys in env variables?

**Comment by itsvikramagr** [comment]
As of now, the code uses the keys set explicitly in the code. But as a fix for https://github.com/qubole/kinesis-sql/issues/4, we can have that support.
